# Docker Compose for local development and testing
# Runs the Chess Platform with all dependencies

version: '3.8'

services:
  chess-platform:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    
  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chess-platform
    restart: unless-stopped